### PR TITLE
Many new cards available for support thanks to our GPU survey. 

### PR DESCRIPTION
**Pull request by KrutavShah**
Thanks to the wonderful community for submitting their PCI IDs and card names in the Discord server. I have added all that people want so far.

### CODE REVIEW

**Comment by DualCoder** [comment]
Please only use unix line endings for code. This makes it much easier to review. `dos2unix` will convert it back to unix line endings.

For example the diff for 2fe296a is huge.

**Comment by jonpas** [comment]
@DualCoder You can make this happen automatically (99% of the time) with a `.gitattributes` file and normalizing all line endings in the repo.

I can PR that if it's wanted along with an EditorConfig. :)

**Comment by DualCoder** [comment]
@jonpas Please do.

**Comment by jonpas** [comment]
#18 but this branch will still have to be updated, as `.gitattributes` only works for new commits / changed lines (if I remember correctly).

**Comment by KrutavShah** [comment]
I'm on windows, so no Unix line endings for me :(

**Comment by KrutavShah** [comment]
I added M10, M60, and V100 support, so I think this PR is completed. Let me know if there is anything else you need before merging :)

**Comment by KrutavShah** [comment]
Changed CRLF to LF, sorry about the difference looking huge.

**Review by DualCoder — CHANGES_REQUESTED** [review]

**Review by DualCoder — APPROVED** [review]

**Pull request merged**
